import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  es: {
    translation: {
      header: { subtitle: 'Sistema de Gestión de Inventarios', logout: 'Cerrar sesión' },
      roles: { admin: 'Admin', seller: 'Vendedor', warehouse: 'Bodeguero', operator: 'Operador' },
      nav: { main: 'Principal', dashboard: 'Dashboard', stock: 'Stock', movements: 'Movimientos', operations: 'Operaciones', purchases: 'Compras', sales: 'Ventas', warehouses: 'Almacenes', analysis: 'Análisis', analytics: 'Analytics IA', reports: 'Reportes', costs: 'Costos', config: 'Config', integrations: 'Integraciones', audit: 'Auditoría', controlTracking: 'Control & Seguimiento' },
      greetings: {
        morning: 'Buenos días',
        afternoon: 'Buenas tardes',
        evening: 'Buenas noches',
      },
      health: {
        excellent: 'Excelente',
        good: 'Bueno',
        needsAttention: 'Necesita atención',
        critical: 'Crítico',
        healthy: 'Saludable',
        warning: 'Advertencia',
      },
      dashboard: { totalValue: 'Valor Total', itemsInStock: 'Items en Stock', lowStock: 'Stock Bajo', movementsToday: 'Movimientos Hoy', smartAlerts: 'Alertas Inteligentes', registerMovement: 'Registrar Movimiento', newProduct: 'Nuevo Producto', entryOrExit: 'Entrada o salida de inventario', addToCatalog: 'Agregar al catálogo', inventoryHealth: 'Salud del Inventario', welcomeSubtitle: 'Aquí está el resumen de tu inventario' },
      stock: { title: 'Stock', search: 'Buscar productos (búsqueda inteligente)...', allCategories: 'Todas las categorías', new: 'Nuevo', import: 'Importar CSV', image: 'Imagen', code: 'Código', description: 'Descripción', category: 'Categoría', warehouse: 'Almacén', price: 'Precio', stockCol: 'Stock', actions: 'Acciones', noWarehouse: 'Sin almacén', noProducts: 'No se encontraron productos', aiActive: 'IA activa', confirmDelete: '¿Estás seguro de eliminar este producto?', editProduct: 'Editar Producto', newProduct: 'Nuevo Producto', salePrice: 'Precio de Venta', minStock: 'Stock Mínimo', selectCategory: 'Seleccionar categoría...', addProduct: 'Agregar Producto', saveChanges: 'Guardar Cambios', currentStock: 'Stock Actual (para ajuste)', productImage: 'Imagen del producto', clickToUpload: 'Click para subir o cambiar', maxSize: 'Máximo 2MB (JPG, PNG)' , selectWarehouse: 'Seleccioná un almacén para ver sus productos', products: 'productos', totalProducts: 'Total de productos', productsWithoutWarehouse: 'Productos sin almacén asignado', initialStock: 'Stock Inicial', initialQuantity: 'Cantidad Inicial', unitCost: 'Costo Unitario', initialStockHint: 'Si agregás stock inicial, se creará automáticamente un movimiento de entrada.'},
      trends: { increasing: 'Subiendo', decreasing: 'Bajando', stable: 'Estable', noData: 'Sin datos' },
      periods: { week: 'Semana', month: 'Mes', semester: 'Semestre', year: 'Año', lastWeek: 'Última semana', lastMonth: 'Último mes', lastSemester: 'Último semestre', lastYear: 'Último año' },
      alerts: { critical: 'Crítica', medium: 'Media', low: 'Baja', noAlerts: 'No hay alertas de stock', noAlertsFilter: 'No hay alertas con este filtro' },
      analytics: { title: 'Análisis Predictivo de Inventario', description: 'Predicciones basadas en patrones históricos de consumo.', noData: 'No hay suficientes datos para generar predicciones.', predictions: 'Predicciones', anomalies: 'Anomalías', associations: 'Asociaciones', modelConfidence: 'Confianza del modelo', currentStock: 'Stock Actual', daysLeft: 'Días Restantes', daysRemaining: 'días restantes', dailyConsumption: 'Consumo/Día', trend: 'Tendencia', topConsumed: 'Productos Más Consumidos', noConsumptionData: 'No hay datos de consumo en este período', clickBarDetails: 'Click en una barra para ver detalles', realConsumption: 'Consumo real', trendLine: 'Línea de tendencia', consumptionIncreasing: 'Consumo en aumento', consumptionDecreasing: 'Consumo en descenso', consumption: 'Consumo', dayAvg: 'día promedio', estimatedCurrentRate: 'Estimado al ritmo actual', recentMovements: 'Últimos Movimientos', noMovementsPeriod: 'No hay movimientos en este período' },
      ai: { active: 'IA Activa', predictions: 'Predicciones IA (Holt-Winters + XGBoost)', anomalies: 'Anomalías (Isolation Forest)', associations: 'Productos Relacionados (Apriori)', noAnomalies: 'No se detectaron anomalías', noAssociations: 'No hay suficientes datos para asociaciones', noCriticalProducts: 'No hay productos críticos', analyzedProducts: 'productos críticos de {total} analizados', analyzedMovements: 'anomalías en {total} movimientos (últimos 30 días)' },
      movements: { title: 'Historial de Movimientos', register: 'Registrar', entry: 'Entrada', exit: 'Salida', product: 'Producto', type: 'Tipo de Movimiento', quantity: 'Cantidad', purchaseCost: 'Costo de Compra (por unidad)', howMuchPaid: '¿A cuánto compraste?', notes: 'Notas (opcional)', notesPlaceholder: 'Ej: Compra proveedor X, Factura #123', user: 'Usuario', noMovements: 'No hay movimientos registrados', registerEntry: 'Registrar Entrada', registerExit: 'Registrar Salida', selectProduct: 'Seleccionar producto...' },
      purchases: { title: 'Compras', suppliers: 'Proveedores', purchaseOrders: 'Órdenes de Compra', newSupplier: 'Nuevo Proveedor', newOrder: 'Nueva Orden', supplier: 'Proveedor', contact: 'Contacto', email: 'Email', phone: 'Teléfono', address: 'Dirección', city: 'Ciudad', country: 'País', notes: 'Notas', searchSuppliers: 'Buscar proveedores...', noSuppliers: 'No hay proveedores registrados', editSupplier: 'Editar Proveedor', createSupplier: 'Crear Proveedor', deactivateSupplier: '¿Desactivar este proveedor?', orderNumber: 'N° Orden', orderDate: 'Fecha Orden', expectedDate: 'Fecha Esperada', status: 'Estado', total: 'Total', noOrders: 'No hay órdenes de compra', loadingSuppliers: 'Cargando proveedores...', loadingOrders: 'Cargando órdenes...', products: 'Productos', addProduct: '+ Agregar producto', selectSupplier: 'Seleccionar proveedor...', selectProduct: 'Seleccionar producto...', quantity: 'Cant.', unitCost: 'Costo/u', createOrder: 'Crear Orden', markAsSent: 'Marcar como Enviada', markAsReceived: 'Marcar como Recibida', received: 'recibidos', states: { draft: 'Borrador', sent: 'Enviada', partial: 'Parcial', received: 'Recibida', cancelled: 'Cancelada' } },
      sales: { title: 'Ventas', customers: 'Clientes', salesOrders: 'Órdenes de Venta', newCustomer: 'Nuevo Cliente', newOrder: 'Nueva Venta', customer: 'Cliente', type: 'Tipo', person: 'Persona', company: 'Empresa', document: 'RUT/CI', creditLimit: 'Límite de Crédito', pendingBalance: 'Saldo Pendiente', owes: 'Debe', noCustomers: 'No hay clientes registrados', searchCustomers: 'Buscar clientes...', loadingCustomers: 'Cargando clientes...', loadingOrders: 'Cargando órdenes...', editCustomer: 'Editar Cliente', createCustomer: 'Crear Cliente', deactivateCustomer: '¿Desactivar este cliente?', orderNumber: 'N° Orden', orderDate: 'Fecha Orden', deliveryDate: 'Fecha Entrega', status: 'Estado', total: 'Total', noOrders: 'No hay órdenes de venta', selectCustomer: 'Seleccionar cliente...', selectProduct: 'Seleccionar producto...', deliveryAddress: 'Dirección de Envío', paymentMethod: 'Método de Pago', paymentMethods: { cash: 'Efectivo', transfer: 'Transferencia', card: 'Tarjeta', credit: 'Crédito' }, createSale: 'Crear Venta', paid: 'Pagado', units: 'unidades', insufficientStock: 'Stock insuficiente', states: { draft: 'Borrador', confirmed: 'Confirmada', inProcess: 'En Proceso', shipped: 'Enviada', delivered: 'Entregada', cancelled: 'Cancelada' }, actions: { confirm: 'Confirmar', inProcess: 'En Proceso', markShipped: 'Marcar Enviada', markDelivered: 'Marcar Entregada' } },
      warehouses: { title: 'Almacenes', transfers: 'Transferencias', newWarehouse: 'Nuevo Almacén', newTransfer: 'Nueva Transferencia', main: 'Principal', address: 'Dirección', city: 'Ciudad', phone: 'Teléfono', manager: 'Responsable', edit: 'Editar', deactivate: '¿Desactivar este almacén?', code: 'Código', name: 'Nombre', editWarehouse: 'Editar Almacén', origin: 'Almacén Origen', destination: 'Almacén Destino', products: 'Productos', addProduct: '+ Agregar producto', createTransfer: 'Crear Transferencia', noTransfers: 'No hay transferencias', send: 'Enviar', confirmReception: 'Confirmar Recepción', selectOrigin: 'Seleccionar...', selectProduct: 'Seleccionar...', units: 'unidades', notesOptional: 'Notas opcionales...', selectOriginDestination: 'Selecciona origen, destino y al menos un producto', states: { pending: 'Pendiente', inTransit: 'En Tránsito', completed: 'Completada', cancelled: 'Cancelada' } },
      costs: { title: 'Análisis de Costos', inventoryCost: 'Costo Inventario (FIFO)', saleValue: 'Valor Venta', grossMargin: 'Margen Bruto', marginPercent: '% Margen', topProducts: 'Top 5 Productos por Valor en Stock', salePrice: 'precio venta', activeLots: 'Lotes Activos', noLots: 'No hay lotes activos', inventoryLots: 'Lotes de Inventario', noLotsRegistered: 'No hay lotes registrados', lot: 'Lote', available: 'Disponible', unitCost: 'Costo Unit.', lotValue: 'Valor Lote', totalStockValue: 'Valor Total en Stock (FIFO)', weightedAvgCost: 'Costo Promedio Ponderado', priceHistory: 'Historial de Precios', changes: 'cambios', noPriceChanges: 'No hay cambios de precio', from: 'De', to: 'A', noProductsWithCost: 'No hay productos con costo registrado' },
      reports: { title: 'Reportes', executiveDashboard: 'Dashboard Ejecutivo', kpiSummary: 'Resumen de KPIs e indicadores clave', exportPDF: 'PDF', exportExcel: 'Excel', inventoryValue: 'Valor del Inventario', itemsInStock: 'Items en Stock', products: 'productos', entriesMonth: 'Entradas del Mes', exitsMonth: 'Salidas del Mes', lowStockProducts: 'Productos Stock Bajo', requiresAttention: 'Requieren atención', outOfStock: 'Productos Sin Stock', depleted: 'Agotados', inventoryRotation: 'Rotación Inventario', avgReplacement: 'Promedio de reposición', days: 'días', topSoldProducts: 'Top 5 Productos Más Vendidos', noSalesThisMonth: 'No hay datos de ventas este mes', categoryDistribution: 'Distribución por Categoría', items: 'items' },
      integrations: { title: 'Integraciones eCommerce', subtitle: 'Conecta tu inventario con tiendas online', shopify: 'Shopify', shopifyDesc: 'Sincroniza productos y órdenes con Shopify', woocommerce: 'WooCommerce', woocommerceDesc: 'Conecta con WordPress + WooCommerce', mercadolibre: 'MercadoLibre', mercadolibreDesc: 'Sincroniza publicaciones y ventas', tiendanube: 'TiendaNube', tiendanubeDesc: 'Integración con TiendaNube', connected: 'Activo', disconnected: 'Inactivo', sync: 'Sincronizar', syncing: 'Sincronizando...', lastSync: 'Última sincronización', noIntegrations: 'Sin integraciones', noIntegrationsDesc: 'Conecta tu primera tienda online', newIntegration: 'Nueva Integración', addIntegration: 'Agregar Integración', editIntegration: 'Editar Integración', configure: 'Configurar', selectPlatform: 'Selecciona la plataforma:', storeName: 'Nombre de la tienda', storeUrl: 'URL de la tienda', apiKey: 'API Key / Client ID', apiSecret: 'API Secret / Access Token', credentialsWarning: 'Las credenciales se guardan de forma segura.', deleteConfirm: '¿Eliminar esta integración?', loading: 'Cargando integraciones...' },
      audit: { title: 'Auditoría del Sistema', description: 'Historial de todas las acciones realizadas', noLogs: 'No hay registros de auditoría', loading: 'Cargando auditoría...', records: 'registros', allTables: 'Todas las tablas', allActions: 'Todas las acciones', in: 'en', system: 'Sistema', previousData: 'Datos anteriores', newData: 'Datos nuevos', tables: { products: 'Productos', movements: 'Movimientos' }, actions: { create: 'Crear', update: 'Actualizar', delete: 'Eliminar' } },
      common: { save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', create: 'Crear', add: 'Agregar', close: 'Cerrar', confirm: 'Confirmar', loading: 'Cargando...', search: 'Buscar', filter: 'Filtrar', export: 'Exportar', import: 'Importar', yes: 'Sí', no: 'No', active: 'Activo', inactive: 'Inactivo', status: 'Estado', date: 'Fecha', total: 'Total', subtotal: 'Subtotal', discount: 'Descuento', taxes: 'Impuestos', noPermission: 'Sin permisos', actions: 'Acciones', select: 'Seleccionar...', suggestion: 'Sugerencia', confidence: 'confianza', apply: 'Aplicar', all: 'Todas', noCategory: 'Sin categoría', perUnit: 'Por unidad', retry: 'Reintentar', noData: 'No hay datos', view: 'Ver', optional: 'opcional'},
      settings: { title: 'Configuración', language: 'Idioma', currency: 'Moneda', theme: 'Tema', themes: { dark: 'Oscuro', light: 'Claro', system: 'Sistema' } },
      currencies: { USD: 'Dólar estadounidense', EUR: 'Euro', UYU: 'Peso uruguayo', ARS: 'Peso argentino', BRL: 'Real brasileño' },
      errors: {
        loadingError: 'Error al cargar',
        tryAgain: 'Intentá de nuevo',
        timeout: 'Tiempo de espera agotado',
        slowConnection: 'La conexión está lenta. Verificá tu internet.',
        offline: 'Sin conexión',
        checkConnection: 'Verificá tu conexión a internet',
        serverError: 'Error del servidor',
        unknownError: 'Error desconocido',
      },
    },
  },
  en: {
    translation: {
      header: { subtitle: 'Inventory Management System', logout: 'Log out' },
      roles: { admin: 'Admin', seller: 'Seller', warehouse: 'Warehouse', operator: 'Operator' },
      nav: { main: 'Main', dashboard: 'Dashboard', stock: 'Stock', movements: 'Movements', operations: 'Operations', purchases: 'Purchases', sales: 'Sales', warehouses: 'Warehouses', analysis: 'Analysis', analytics: 'AI Analytics', reports: 'Reports', costs: 'Costs', config: 'Config', integrations: 'Integrations', audit: 'Audit', controlTracking: 'Control & Tracking' },
      greetings: {
        morning: 'Good morning',
        afternoon: 'Good afternoon',
        evening: 'Good evening',
      },
      health: {
        excellent: 'Excellent',
        good: 'Good',
        needsAttention: 'Needs attention',
        critical: 'Critical',
        healthy: 'Healthy',
        warning: 'Warning',
      },
      dashboard: { totalValue: 'Total Value', itemsInStock: 'Items in Stock', lowStock: 'Low Stock', movementsToday: 'Movements Today', smartAlerts: 'Smart Alerts', registerMovement: 'Register Movement', newProduct: 'New Product', entryOrExit: 'Inventory entry or exit', addToCatalog: 'Add to catalog', inventoryHealth: 'Inventory Health', welcomeSubtitle: 'Here is your inventory summary' },
      stock: { title: 'Stock', search: 'Search products (smart search)...', allCategories: 'All categories', new: 'New', import: 'Import CSV', image: 'Image', code: 'Code', description: 'Description', category: 'Category', warehouse: 'Warehouse', price: 'Price', stockCol: 'Stock', actions: 'Actions', noWarehouse: 'No warehouse', noProducts: 'No products found', aiActive: 'AI active', confirmDelete: 'Are you sure you want to delete this product?', editProduct: 'Edit Product', newProduct: 'New Product', salePrice: 'Sale Price', minStock: 'Minimum Stock', selectCategory: 'Select category...', addProduct: 'Add Product', saveChanges: 'Save Changes', currentStock: 'Current Stock (for adjustment)', productImage: 'Product image', clickToUpload: 'Click to upload or change', maxSize: 'Maximum 2MB (JPG, PNG)', selectWarehouse: 'Select a warehouse to view its products', products: 'products', totalProducts: 'Total products', productsWithoutWarehouse: 'Products without assigned warehouse', initialStock: 'Initial Stock', initialQuantity: 'Initial Quantity', unitCost: 'Unit Cost', initialStockHint: 'If you add initial stock, an entry movement will be created automatically.' },
      trends: { increasing: 'Increasing', decreasing: 'Decreasing', stable: 'Stable', noData: 'No data' },
      periods: { week: 'Week', month: 'Month', semester: 'Semester', year: 'Year', lastWeek: 'Last week', lastMonth: 'Last month', lastSemester: 'Last semester', lastYear: 'Last year' },
      alerts: { critical: 'Critical', medium: 'Medium', low: 'Low', noAlerts: 'No stock alerts', noAlertsFilter: 'No alerts with this filter' },
      analytics: { title: 'Predictive Inventory Analysis', description: 'Predictions based on historical consumption patterns.', noData: 'Not enough data to generate predictions.', predictions: 'Predictions', anomalies: 'Anomalies', associations: 'Associations', modelConfidence: 'Model confidence', currentStock: 'Current Stock', daysLeft: 'Days Left', daysRemaining: 'days remaining', dailyConsumption: 'Daily Consumption', trend: 'Trend', topConsumed: 'Top Consumed Products', noConsumptionData: 'No consumption data in this period', clickBarDetails: 'Click on a bar to see details', realConsumption: 'Real consumption', trendLine: 'Trend line', consumptionIncreasing: 'Consumption increasing', consumptionDecreasing: 'Consumption decreasing', consumption: 'Consumption', dayAvg: 'day average', estimatedCurrentRate: 'Estimated at current rate', recentMovements: 'Recent Movements', noMovementsPeriod: 'No movements in this period' },
      ai: { active: 'AI Active', predictions: 'AI Predictions (Holt-Winters + XGBoost)', anomalies: 'Anomalies (Isolation Forest)', associations: 'Related Products (Apriori)', noAnomalies: 'No anomalies detected', noAssociations: 'Not enough data for associations', noCriticalProducts: 'No critical products', analyzedProducts: 'critical products of {total} analyzed', analyzedMovements: 'anomalies in {total} movements (last 30 days)' },
      movements: { title: 'Movement History', register: 'Register', entry: 'Entry', exit: 'Exit', product: 'Product', type: 'Movement Type', quantity: 'Quantity', purchaseCost: 'Purchase Cost (per unit)', howMuchPaid: 'How much did you pay?', notes: 'Notes (optional)', notesPlaceholder: 'Ex: Supplier X purchase, Invoice #123', user: 'User', noMovements: 'No movements registered', registerEntry: 'Register Entry', registerExit: 'Register Exit', selectProduct: 'Select product...' },
      purchases: { title: 'Purchases', suppliers: 'Suppliers', purchaseOrders: 'Purchase Orders', newSupplier: 'New Supplier', newOrder: 'New Order', supplier: 'Supplier', contact: 'Contact', email: 'Email', phone: 'Phone', address: 'Address', city: 'City', country: 'Country', notes: 'Notes', searchSuppliers: 'Search suppliers...', noSuppliers: 'No suppliers registered', editSupplier: 'Edit Supplier', createSupplier: 'Create Supplier', deactivateSupplier: 'Deactivate this supplier?', orderNumber: 'Order #', orderDate: 'Order Date', expectedDate: 'Expected Date', status: 'Status', total: 'Total', noOrders: 'No purchase orders', loadingSuppliers: 'Loading suppliers...', loadingOrders: 'Loading orders...', products: 'Products', addProduct: '+ Add product', selectSupplier: 'Select supplier...', selectProduct: 'Select product...', quantity: 'Qty', unitCost: 'Cost/u', createOrder: 'Create Order', markAsSent: 'Mark as Sent', markAsReceived: 'Mark as Received', received: 'received', states: { draft: 'Draft', sent: 'Sent', partial: 'Partial', received: 'Received', cancelled: 'Cancelled' } },
      sales: { title: 'Sales', customers: 'Customers', salesOrders: 'Sales Orders', newCustomer: 'New Customer', newOrder: 'New Sale', customer: 'Customer', type: 'Type', person: 'Person', company: 'Company', document: 'Tax ID', creditLimit: 'Credit Limit', pendingBalance: 'Pending Balance', owes: 'Owes', noCustomers: 'No customers registered', searchCustomers: 'Search customers...', loadingCustomers: 'Loading customers...', loadingOrders: 'Loading orders...', editCustomer: 'Edit Customer', createCustomer: 'Create Customer', deactivateCustomer: 'Deactivate this customer?', orderNumber: 'Order #', orderDate: 'Order Date', deliveryDate: 'Delivery Date', status: 'Status', total: 'Total', noOrders: 'No sales orders', selectCustomer: 'Select customer...', selectProduct: 'Select product...', deliveryAddress: 'Delivery Address', paymentMethod: 'Payment Method', paymentMethods: { cash: 'Cash', transfer: 'Transfer', card: 'Card', credit: 'Credit' }, createSale: 'Create Sale', paid: 'Paid', units: 'units', insufficientStock: 'Insufficient stock', states: { draft: 'Draft', confirmed: 'Confirmed', inProcess: 'In Process', shipped: 'Shipped', delivered: 'Delivered', cancelled: 'Cancelled' }, actions: { confirm: 'Confirm', inProcess: 'In Process', markShipped: 'Mark Shipped', markDelivered: 'Mark Delivered' } },
      warehouses: { title: 'Warehouses', transfers: 'Transfers', newWarehouse: 'New Warehouse', newTransfer: 'New Transfer', main: 'Main', address: 'Address', city: 'City', phone: 'Phone', manager: 'Manager', edit: 'Edit', deactivate: 'Deactivate this warehouse?', code: 'Code', name: 'Name', editWarehouse: 'Edit Warehouse', origin: 'Origin Warehouse', destination: 'Destination Warehouse', products: 'Products', addProduct: '+ Add product', createTransfer: 'Create Transfer', noTransfers: 'No transfers', send: 'Send', confirmReception: 'Confirm Reception', selectOrigin: 'Select...', selectProduct: 'Select...', units: 'units', notesOptional: 'Optional notes...', selectOriginDestination: 'Select origin, destination and at least one product', states: { pending: 'Pending', inTransit: 'In Transit', completed: 'Completed', cancelled: 'Cancelled' } },
      costs: { title: 'Cost Analysis', inventoryCost: 'Inventory Cost (FIFO)', saleValue: 'Sale Value', grossMargin: 'Gross Margin', marginPercent: 'Margin %', topProducts: 'Top 5 Products by Stock Value', salePrice: 'sale price', activeLots: 'Active Lots', noLots: 'No active lots', inventoryLots: 'Inventory Lots', noLotsRegistered: 'No lots registered', lot: 'Lot', available: 'Available', unitCost: 'Unit Cost', lotValue: 'Lot Value', totalStockValue: 'Total Stock Value (FIFO)', weightedAvgCost: 'Weighted Average Cost', priceHistory: 'Price History', changes: 'changes', noPriceChanges: 'No price changes', from: 'From', to: 'To', noProductsWithCost: 'No products with registered cost' },
      reports: { title: 'Reports', executiveDashboard: 'Executive Dashboard', kpiSummary: 'KPIs and key indicators summary', exportPDF: 'PDF', exportExcel: 'Excel', inventoryValue: 'Inventory Value', itemsInStock: 'Items in Stock', products: 'products', entriesMonth: 'Entries This Month', exitsMonth: 'Exits This Month', lowStockProducts: 'Low Stock Products', requiresAttention: 'Require attention', outOfStock: 'Out of Stock', depleted: 'Depleted', inventoryRotation: 'Inventory Rotation', avgReplacement: 'Average replacement', days: 'days', topSoldProducts: 'Top 5 Best Selling Products', noSalesThisMonth: 'No sales data this month', categoryDistribution: 'Category Distribution', items: 'items' },
      integrations: { title: 'eCommerce Integrations', subtitle: 'Connect your inventory with online stores', shopify: 'Shopify', shopifyDesc: 'Sync products and orders with Shopify', woocommerce: 'WooCommerce', woocommerceDesc: 'Connect with WordPress + WooCommerce', mercadolibre: 'MercadoLibre', mercadolibreDesc: 'Sync listings and sales', tiendanube: 'TiendaNube', tiendanubeDesc: 'TiendaNube integration', connected: 'Active', disconnected: 'Inactive', sync: 'Sync', syncing: 'Syncing...', lastSync: 'Last sync', noIntegrations: 'No integrations', noIntegrationsDesc: 'Connect your first online store', newIntegration: 'New Integration', addIntegration: 'Add Integration', editIntegration: 'Edit Integration', configure: 'Configure', selectPlatform: 'Select platform:', storeName: 'Store name', storeUrl: 'Store URL', apiKey: 'API Key / Client ID', apiSecret: 'API Secret / Access Token', credentialsWarning: 'Credentials are stored securely.', deleteConfirm: 'Delete this integration?', loading: 'Loading integrations...' },
      audit: { title: 'System Audit', description: 'History of all actions performed', noLogs: 'No audit logs', loading: 'Loading audit...', records: 'records', allTables: 'All tables', allActions: 'All actions', in: 'in', system: 'System', previousData: 'Previous data', newData: 'New data', tables: { products: 'Products', movements: 'Movements' }, actions: { create: 'Create', update: 'Update', delete: 'Delete' } },
      common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', create: 'Create', add: 'Add', close: 'Close', confirm: 'Confirm', loading: 'Loading...', search: 'Search', filter: 'Filter', export: 'Export', import: 'Import', yes: 'Yes', no: 'No', active: 'Active', inactive: 'Inactive', status: 'Status', date: 'Date', total: 'Total', subtotal: 'Subtotal', discount: 'Discount', taxes: 'Taxes', noPermission: 'No permission', actions: 'Actions', select: 'Select...', suggestion: 'Suggestion', confidence: 'confidence', apply: 'Apply', all: 'All', noCategory: 'No category', perUnit: 'Per unit', retry: 'Retry', noData: 'No data', view: 'View', optional: 'optional' },
      settings: { title: 'Settings', language: 'Language', currency: 'Currency', theme: 'Theme', themes: { dark: 'Dark', light: 'Light', system: 'System' } },
      currencies: { USD: 'US Dollar', EUR: 'Euro', UYU: 'Uruguayan Peso', ARS: 'Argentine Peso', BRL: 'Brazilian Real' },
      errors: {
        loadingError: 'Loading error',
        tryAgain: 'Please try again',
        timeout: 'Request timed out',
        slowConnection: 'Connection is slow. Check your internet.',
        offline: 'No connection',
        checkConnection: 'Check your internet connection',
        serverError: 'Server error',
        unknownError: 'Unknown error',
      },
    },
  },
  pt: {
    translation: {
      header: { subtitle: 'Sistema de Gestão de Inventário', logout: 'Sair' },
      roles: { admin: 'Admin', seller: 'Vendedor', warehouse: 'Armazém', operator: 'Operador' },
      nav: { main: 'Principal', dashboard: 'Painel', stock: 'Estoque', movements: 'Movimentos', operations: 'Operações', purchases: 'Compras', sales: 'Vendas', warehouses: 'Armazéns', analysis: 'Análise', analytics: 'Analytics IA', reports: 'Relatórios', costs: 'Custos', config: 'Config', integrations: 'Integrações', audit: 'Auditoria', controlTracking: 'Controle & Rastreamento' },
      greetings: {
        morning: 'Bom dia',
        afternoon: 'Boa tarde',
        evening: 'Boa noite',
      },
      health: {
        excellent: 'Excelente',
        good: 'Bom',
        needsAttention: 'Precisa de atenção',
        critical: 'Crítico',
        healthy: 'Saudável',
        warning: 'Aviso',
      },
      dashboard: { totalValue: 'Valor Total', itemsInStock: 'Itens em Estoque', lowStock: 'Estoque Baixo', movementsToday: 'Movimentos Hoje', smartAlerts: 'Alertas Inteligentes', registerMovement: 'Registrar Movimento', newProduct: 'Novo Produto', entryOrExit: 'Entrada ou saída de estoque', addToCatalog: 'Adicionar ao catálogo', inventoryHealth: 'Saúde do Inventário', welcomeSubtitle: 'Aqui está o resumo do seu inventário' },
      stock: { title: 'Estoque', search: 'Buscar produtos (busca inteligente)...', allCategories: 'Todas as categorias', new: 'Novo', import: 'Importar CSV', image: 'Imagem', code: 'Código', description: 'Descrição', category: 'Categoria', warehouse: 'Armazém', price: 'Preço', stockCol: 'Estoque', actions: 'Ações', noWarehouse: 'Sem armazém', noProducts: 'Nenhum produto encontrado', aiActive: 'IA ativa', confirmDelete: 'Tem certeza que deseja excluir este produto?', editProduct: 'Editar Produto', newProduct: 'Novo Produto', salePrice: 'Preço de Venda', minStock: 'Estoque Mínimo', selectCategory: 'Selecionar categoria...', addProduct: 'Adicionar Produto', saveChanges: 'Salvar Alterações', currentStock: 'Estoque Atual (para ajuste)', productImage: 'Imagem do produto', clickToUpload: 'Clique para enviar ou alterar', maxSize: 'Máximo 2MB (JPG, PNG)', selectWarehouse: 'Selecione um armazém para ver seus produtos', products: 'produtos', totalProducts: 'Total de produtos', productsWithoutWarehouse: 'Produtos sem armazém atribuído', initialStock: 'Estoque Inicial', initialQuantity: 'Quantidade Inicial', unitCost: 'Custo Unitário', initialStockHint: 'Se você adicionar estoque inicial, um movimento de entrada será criado automaticamente.' },
      trends: { increasing: 'Aumentando', decreasing: 'Diminuindo', stable: 'Estável', noData: 'Sem dados' },
      periods: { week: 'Semana', month: 'Mês', semester: 'Semestre', year: 'Ano', lastWeek: 'Última semana', lastMonth: 'Último mês', lastSemester: 'Último semestre', lastYear: 'Último ano' },
      alerts: { critical: 'Crítica', medium: 'Média', low: 'Baixa', noAlerts: 'Sem alertas de estoque', noAlertsFilter: 'Sem alertas com este filtro' },
      analytics: { title: 'Análise Preditiva de Inventário', description: 'Previsões baseadas em padrões históricos de consumo.', noData: 'Dados insuficientes para gerar previsões.', predictions: 'Previsões', anomalies: 'Anomalias', associations: 'Associações', modelConfidence: 'Confiança do modelo', currentStock: 'Estoque Atual', daysLeft: 'Dias Restantes', daysRemaining: 'dias restantes', dailyConsumption: 'Consumo/Dia', trend: 'Tendência', topConsumed: 'Produtos Mais Consumidos', noConsumptionData: 'Sem dados de consumo neste período', clickBarDetails: 'Clique em uma barra para ver detalhes', realConsumption: 'Consumo real', trendLine: 'Linha de tendência', consumptionIncreasing: 'Consumo aumentando', consumptionDecreasing: 'Consumo diminuindo', consumption: 'Consumo', dayAvg: 'média diária', estimatedCurrentRate: 'Estimado no ritmo atual', recentMovements: 'Movimentos Recentes', noMovementsPeriod: 'Sem movimentos neste período' },
      ai: { active: 'IA Ativa', predictions: 'Previsões IA (Holt-Winters + XGBoost)', anomalies: 'Anomalias (Isolation Forest)', associations: 'Produtos Relacionados (Apriori)', noAnomalies: 'Nenhuma anomalia detectada', noAssociations: 'Dados insuficientes para associações', noCriticalProducts: 'Sem produtos críticos', analyzedProducts: 'produtos críticos de {total} analisados', analyzedMovements: 'anomalias em {total} movimentos (últimos 30 dias)' },
      movements: { title: 'Histórico de Movimentos', register: 'Registrar', entry: 'Entrada', exit: 'Saída', product: 'Produto', type: 'Tipo de Movimento', quantity: 'Quantidade', purchaseCost: 'Custo de Compra (por unidade)', howMuchPaid: 'Quanto você pagou?', notes: 'Notas (opcional)', notesPlaceholder: 'Ex: Compra fornecedor X, Fatura #123', user: 'Usuário', noMovements: 'Nenhum movimento registrado', registerEntry: 'Registrar Entrada', registerExit: 'Registrar Saída', selectProduct: 'Selecionar produto...' },
      purchases: { title: 'Compras', suppliers: 'Fornecedores', purchaseOrders: 'Ordens de Compra', newSupplier: 'Novo Fornecedor', newOrder: 'Nova Ordem', supplier: 'Fornecedor', contact: 'Contato', email: 'Email', phone: 'Telefone', address: 'Endereço', city: 'Cidade', country: 'País', notes: 'Notas', searchSuppliers: 'Buscar fornecedores...', noSuppliers: 'Nenhum fornecedor registrado', editSupplier: 'Editar Fornecedor', createSupplier: 'Criar Fornecedor', deactivateSupplier: 'Desativar este fornecedor?', orderNumber: 'N° Ordem', orderDate: 'Data da Ordem', expectedDate: 'Data Esperada', status: 'Status', total: 'Total', noOrders: 'Nenhuma ordem de compra', loadingSuppliers: 'Carregando fornecedores...', loadingOrders: 'Carregando ordens...', products: 'Produtos', addProduct: '+ Adicionar produto', selectSupplier: 'Selecionar fornecedor...', selectProduct: 'Selecionar produto...', quantity: 'Qtd', unitCost: 'Custo/u', createOrder: 'Criar Ordem', markAsSent: 'Marcar como Enviada', markAsReceived: 'Marcar como Recebida', received: 'recebidos', states: { draft: 'Rascunho', sent: 'Enviada', partial: 'Parcial', received: 'Recebida', cancelled: 'Cancelada' } },
      sales: { title: 'Vendas', customers: 'Clientes', salesOrders: 'Ordens de Venda', newCustomer: 'Novo Cliente', newOrder: 'Nova Venda', customer: 'Cliente', type: 'Tipo', person: 'Pessoa', company: 'Empresa', document: 'CPF/CNPJ', creditLimit: 'Limite de Crédito', pendingBalance: 'Saldo Pendente', owes: 'Deve', noCustomers: 'Nenhum cliente registrado', searchCustomers: 'Buscar clientes...', loadingCustomers: 'Carregando clientes...', loadingOrders: 'Carregando ordens...', editCustomer: 'Editar Cliente', createCustomer: 'Criar Cliente', deactivateCustomer: 'Desativar este cliente?', orderNumber: 'N° Ordem', orderDate: 'Data da Ordem', deliveryDate: 'Data de Entrega', status: 'Status', total: 'Total', noOrders: 'Nenhuma ordem de venda', selectCustomer: 'Selecionar cliente...', selectProduct: 'Selecionar produto...', deliveryAddress: 'Endereço de Entrega', paymentMethod: 'Método de Pagamento', paymentMethods: { cash: 'Dinheiro', transfer: 'Transferência', card: 'Cartão', credit: 'Crédito' }, createSale: 'Criar Venda', paid: 'Pago', units: 'unidades', insufficientStock: 'Estoque insuficiente', states: { draft: 'Rascunho', confirmed: 'Confirmada', inProcess: 'Em Processo', shipped: 'Enviada', delivered: 'Entregue', cancelled: 'Cancelada' }, actions: { confirm: 'Confirmar', inProcess: 'Em Processo', markShipped: 'Marcar Enviada', markDelivered: 'Marcar Entregue' } },
      warehouses: { title: 'Armazéns', transfers: 'Transferências', newWarehouse: 'Novo Armazém', newTransfer: 'Nova Transferência', main: 'Principal', address: 'Endereço', city: 'Cidade', phone: 'Telefone', manager: 'Responsável', edit: 'Editar', deactivate: 'Desativar este armazém?', code: 'Código', name: 'Nome', editWarehouse: 'Editar Armazém', origin: 'Armazém Origem', destination: 'Armazém Destino', products: 'Produtos', addProduct: '+ Adicionar produto', createTransfer: 'Criar Transferência', noTransfers: 'Sem transferências', send: 'Enviar', confirmReception: 'Confirmar Recebimento', selectOrigin: 'Selecionar...', selectProduct: 'Selecionar...', units: 'unidades', notesOptional: 'Notas opcionais...', selectOriginDestination: 'Selecione origem, destino e pelo menos um produto', states: { pending: 'Pendente', inTransit: 'Em Trânsito', completed: 'Concluída', cancelled: 'Cancelada' } },
      costs: { title: 'Análise de Custos', inventoryCost: 'Custo Estoque (FIFO)', saleValue: 'Valor Venda', grossMargin: 'Margem Bruta', marginPercent: '% Margem', topProducts: 'Top 5 Produtos por Valor em Estoque', salePrice: 'preço venda', activeLots: 'Lotes Ativos', noLots: 'Não há lotes ativos', inventoryLots: 'Lotes de Inventário', noLotsRegistered: 'Nenhum lote registrado', lot: 'Lote', available: 'Disponível', unitCost: 'Custo Unit.', lotValue: 'Valor Lote', totalStockValue: 'Valor Total em Estoque (FIFO)', weightedAvgCost: 'Custo Médio Ponderado', priceHistory: 'Histórico de Preços', changes: 'alterações', noPriceChanges: 'Sem alterações de preço', from: 'De', to: 'Para', noProductsWithCost: 'Nenhum produto com custo registrado' },
      reports: { title: 'Relatórios', executiveDashboard: 'Dashboard Executivo', kpiSummary: 'Resumo de KPIs e indicadores chave', exportPDF: 'PDF', exportExcel: 'Excel', inventoryValue: 'Valor do Inventário', itemsInStock: 'Itens em Estoque', products: 'produtos', entriesMonth: 'Entradas do Mês', exitsMonth: 'Saídas do Mês', lowStockProducts: 'Produtos Estoque Baixo', requiresAttention: 'Requerem atenção', outOfStock: 'Sem Estoque', depleted: 'Esgotados', inventoryRotation: 'Rotação de Inventário', avgReplacement: 'Média de reposição', days: 'dias', topSoldProducts: 'Top 5 Produtos Mais Vendidos', noSalesThisMonth: 'Sem dados de vendas este mês', categoryDistribution: 'Distribuição por Categoria', items: 'itens' },
      integrations: { title: 'Integrações eCommerce', subtitle: 'Conecte seu inventário com lojas online', shopify: 'Shopify', shopifyDesc: 'Sincronize produtos e pedidos com Shopify', woocommerce: 'WooCommerce', woocommerceDesc: 'Conecte com WordPress + WooCommerce', mercadolibre: 'MercadoLibre', mercadolibreDesc: 'Sincronize anúncios e vendas', tiendanube: 'TiendaNube', tiendanubeDesc: 'Integração com TiendaNube', connected: 'Ativo', disconnected: 'Inativo', sync: 'Sincronizar', syncing: 'Sincronizando...', lastSync: 'Última sincronização', noIntegrations: 'Sem integrações', noIntegrationsDesc: 'Conecte sua primeira loja online', newIntegration: 'Nova Integração', addIntegration: 'Adicionar Integração', editIntegration: 'Editar Integração', configure: 'Configurar', selectPlatform: 'Selecione a plataforma:', storeName: 'Nome da loja', storeUrl: 'URL da loja', apiKey: 'API Key / Client ID', apiSecret: 'API Secret / Access Token', credentialsWarning: 'As credenciais são armazenadas de forma segura.', deleteConfirm: 'Excluir esta integração?', loading: 'Carregando integrações...' },
      audit: { title: 'Auditoria do Sistema', description: 'Histórico de todas as ações realizadas', noLogs: 'Nenhum registro de auditoria', loading: 'Carregando auditoria...', records: 'registros', allTables: 'Todas as tabelas', allActions: 'Todas as ações', in: 'em', system: 'Sistema', previousData: 'Dados anteriores', newData: 'Novos dados', tables: { products: 'Produtos', movements: 'Movimentos' }, actions: { create: 'Criar', update: 'Atualizar', delete: 'Excluir' } },
      common: { save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', create: 'Criar', add: 'Adicionar', close: 'Fechar', confirm: 'Confirmar', loading: 'Carregando...', search: 'Buscar', filter: 'Filtrar', export: 'Exportar', import: 'Importar', yes: 'Sim', no: 'Não', active: 'Ativo', inactive: 'Inativo', status: 'Status', date: 'Data', total: 'Total', subtotal: 'Subtotal', discount: 'Desconto', taxes: 'Impostos', noPermission: 'Sem permissão', actions: 'Ações', select: 'Selecionar...', suggestion: 'Sugestão', confidence: 'confiança', apply: 'Aplicar', all: 'Todas', noCategory: 'Sem categoria', perUnit: 'Por unidade', retry: 'Tentar novamente', noData: 'Sem dados', view: 'Ver', optional: 'opcional' },
      settings: { title: 'Configurações', language: 'Idioma', currency: 'Moeda', theme: 'Tema', themes: { dark: 'Escuro', light: 'Claro', system: 'Sistema' } },
      currencies: { USD: 'Dólar americano', EUR: 'Euro', UYU: 'Peso uruguaio', ARS: 'Peso argentino', BRL: 'Real brasileiro' },
      errors: {
        loadingError: 'Erro ao carregar',
        tryAgain: 'Tente novamente',
        timeout: 'Tempo de espera esgotado',
        slowConnection: 'Conexão lenta. Verifique sua internet.',
        offline: 'Sem conexão',
        checkConnection: 'Verifique sua conexão com a internet',
        serverError: 'Erro do servidor',
        unknownError: 'Erro desconhecido',
      },
    },
  },
};

const getBrowserLanguage = (): string => {
  if (typeof window === 'undefined') return 'es';
  const lang = navigator.language.split('-')[0];
  return ['es', 'en', 'pt'].includes(lang) ? lang : 'es';
};

const getSavedLanguage = (): string => {
  if (typeof window === 'undefined') return 'es';
  return localStorage.getItem('vanguard_language') || getBrowserLanguage();
};

i18n.use(initReactI18next).init({
  resources,
  lng: getSavedLanguage(),
  fallbackLng: 'es',
  interpolation: { escapeValue: false },
});

export default i18n;

export const changeLanguage = (lang: string) => {
  i18n.changeLanguage(lang);
  if (typeof window !== 'undefined') {
    localStorage.setItem('vanguard_language', lang);
  }
};

export const availableLanguages = [
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
];